language: scala
sudo: false
scala:
- 2.12.1
script: sbt clean test
jdk:
- oraclejdk8
notifications:
  email:
    recipients:
    - karel@geovise.com

env:
  global:
  - secure: iCwqBBum/fSjOFJEsei4G9KQ5U5XnsYlAhJW7cgl9/wCqxDMP6E26vI9UidnkPnMzCYSWVEJEpxioqO9loNIUD6uGDkGgsihQDd3Til7yWVA3Zm4U7sV0XCsCq+1HYljPNTkaneWLSUfrkjsQLLC1f0iDUxDPH9vcbC7sWe0Fd4=
  - secure: aMx1htKJD2dlUWlF73DRVWGOU+WoiL3dtkxg/p1DP6erTyd/BYiW+Z3oPy3mgymD375GICjv/YtllkXB2EFLjPFKli53vOTwBfR5cx/P5/00Cc/lwixERxKgBKOFdLi3hs30x7ecPNaBuh8DYHGqCtsqIn8geh7audqNO1diiac=

after_success:
- '[[ $TRAVIS_BRANCH == "develop" ]] && { sbt +publish; };'
